Repository CBIIT/bento-gmb-frontend, pull requests merged in 2022-05, with the labels that each got.

#41 Local find
  public/index.html
  src/bento/dashboardData.js
  src/bento/globalFooterData.js
  src/bento/localSearchData.js
  src/bento/tableDownloadCSV.js
  src/components/ActiveFiltersQuery/ActiveFiltersQuery.js
  src/components/SideBar/SideBarComponents/CasesModal/SummaryTable.js
  src/components/SideBar/SideBarComponents/CasesModal/index.js
  src/components/SideBar/SideBarComponents/searchComponet.js
  src/pages/search/components/cards/fileCard.js
Labels: 🚧 Do not merge

#50 Merging Develop to v1.0.0
  public/index.html
  src/bento/dashboardData.js
  src/bento/dashboardTabData.js
  src/bento/globalFooterData.js
  src/bento/localSearchData.js
  src/bento/tableDownloadCSV.js
  src/components/ActiveFiltersQuery/ActiveFiltersQuery.js
  src/components/SideBar/SideBarComponents/CasesModal/SummaryTable.js
  src/components/SideBar/SideBarComponents/CasesModal/index.js
  src/components/SideBar/SideBarComponents/FacetFilters.js
  src/components/SideBar/SideBarComponents/searchComponet.js
  src/pages/search/components/cards/fileCard.js
  src/pages/search/components/cards/subjectCard.js
Labels: Develop -> Release

#60 Develop
  public/injectEnv.js
  src/bento/globalFooterData.js
  src/bento/tableDownloadCSV.js
  src/bento/trialDetailData.js
  src/bento/trialsData.js
  src/components/Footer/FooterView.js
  src/components/SideBar/SideBarComponents/searchComponet.js
  src/pages/dashboardTab/components/tabController.js
  src/pages/dashboardTab/store/dashboardReducer.js
  src/pages/siteDetail/siteDetailView.js
  src/pages/trialDetail/trialDetailView.js
Labels: 🚧 Do not merge, Develop -> Release
